services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: proxyscaler
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--accept-routes
    env_file: .env
    volumes:
      - ./data/tailscale:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    ports:
      - 80:80
      - 443:443

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx-proxy-manager:/data
      - ./data/letsencrypt:/etc/letsencrypt
    network_mode: service:tailscale
